CREATE TABLE "public"."t_mem_personal_data" (
  "id" int8 NOT NULL,
  "address" varchar(255),
  "area" varchar(255),
  "area_id" int8,
  "birthday" timestamp(6),
  "blood_type" varchar(255),
  "city" varchar(255),
  "city_id" int8,
  "company" varchar(255),
  "country" varchar(255),
  "country_id" int8,
  "credentials_no" varchar(255),
  "credentials_type" int4,
  "edu" varchar(255),
  "email" varchar(255),
  "industy" varchar(255),
  "intel_real_name" varchar(255),
  "interest" varchar(255),
  "local_real_name" varchar(255),
  "long1" varchar(255),
  "long2" varchar(255),
  "long3" varchar(255),
  "long4" varchar(255),
  "long5" varchar(255),
  "marriage" varchar(255),
  "mobile" varchar(255),
  "nickname" varchar(255),
  "position" varchar(255),
  "postcode" varchar(255),
  "province" varchar(255),
  "province_id" int8,
  "qq" varchar(255),
  "receivemail" int4,
  "salary" varchar(255),
  "sex" int4,
  "short1" varchar(255),
  "short2" varchar(255),
  "short3" varchar(255),
  "short4" varchar(255),
  "short5" varchar(255),
  "town" varchar(255),
  "town_id" int8,
  "user_pic" varchar(255),
  "version" timestamp(6),
  "weibo" varchar(255),
  "weixin" varchar(255),
  "working_life" varchar(255),
  "third_mobile" varchar(255),
  CONSTRAINT "t_mem_personal_data_pkey" PRIMARY KEY ("id")
);
CREATE TABLE "public"."t_mem_contact" (
  "id" int8 NOT NULL,
  "address" varchar(500),
  "area" varchar(255),
  "area_id" int8,
  "city" varchar(255),
  "city_id" int8,
  "contact_type" varchar(255),
  "country" varchar(255),
  "country_id" int8,
  "email" varchar(255),
  "is_default" bool,
  "member_id" int8,
  "mobile" varchar(255),
  "modifytime" timestamp(6),
  "name" varchar(100),
  "post_code" varchar(255),
  "province" varchar(255),
  "province_id" int8,
  "telphone" varchar(255),
  "town" varchar(255),
  "town_id" int8,
  "version" timestamp(6),
  CONSTRAINT "t_mem_contact_pkey" PRIMARY KEY ("id")
);
CREATE TABLE "public"."t_mem_conduct" (
  "id" int8 NOT NULL,
  "client_identification_mechanisms" varchar(255),
  "cumulative_con_amount" numeric(19,2),
  "login_count" int4,
  "login_ip" varchar(255),
  "login_time" timestamp(6),
  "pay_time" timestamp(6),
  "register_client_identification_mechanisms" varchar(255),
  "register_ip" varchar(255),
  "register_time" timestamp(6),
  "version" timestamp(6),
  CONSTRAINT "t_mem_conduct_pkey" PRIMARY KEY ("id")
);
CREATE TABLE "public"."t_sys_coupon_log" (
  "id" int8 NOT NULL,
  "createtime" timestamp(6),
  "memberid" int8,
  "promotioncouponcode" varchar(255),
  "promotioncouponcodeid" int8,
  "promotioncouponid" int8,
  "promotioncouponname" varchar(255),
  CONSTRAINT "t_sys_coupon_log_pkey" PRIMARY KEY ("id")
);
CREATE TABLE "public"."t_crm_email_subscribe_log" (
  "id" int8 NOT NULL,
  "agreed" varchar(255),
  "create_time" timestamp(6),
  "link" varchar(255),
  "member_id" int8,
  CONSTRAINT "t_crm_email_subscribe_log_pkey" PRIMARY KEY ("id")
);
CREATE TABLE "public"."t_mem_member" (
  "id" int8 NOT NULL,
  "group_id" int8,
  "lifecycle" int4,
  "login_email" varchar(255),
  "login_mobile" varchar(255),
  "login_name" varchar(255),
  "oldpassword" varchar(255),
  "password" varchar(255),
  "receive_mail" int4,
  "salt" varchar(255),
  "source" int4,
  "third_party_identify" varchar(512),
  "type" int4,
  "version" timestamp(6),
  "create_time" timestamp(6),
  "customer_no" varchar(255),
  CONSTRAINT "t_mem_member_pkey" PRIMARY KEY ("id"),
  CONSTRAINT "t_mem_member_login_name_login_email_login_mobile_key" UNIQUE ("login_name", "login_email", "login_mobile")
);