CREATE TABLE "public"."t_so_salesorder" (
  "id" int8 NOT NULL,
  "account_bank_name" varchar(255),
  "account_bank_number" varchar(255),
  "actual_freight" numeric(19,2),
  "appoint_ship_date" timestamp(6),
  "client_identification_mechanisms" varchar(255),
  "cod_payment_type" int4,
  "code" varchar(50),
  "company_address" varchar(255),
  "company_phone" varchar(255),
  "create_time" timestamp(6),
  "discount" numeric(19,2),
  "financial_status" int4,
  "guest_identify" varchar(200),
  "invoice_type" int4,
  "ip" varchar(50),
  "is_qs" bool,
  "lang" varchar(255),
  "logistics_provider_code" varchar(255),
  "logistics_provider_name" varchar(255),
  "logistics_status" int4,
  "member_id" int8,
  "member_name" varchar(100),
  "modify_time" timestamp(6),
  "oms_code" varchar(50),
  "order_type" int4,
  "pay_type" int4,
  "payable_freight" numeric(19,2),
  "payment" int4,
  "quantity" int4,
  "receipt_address" varchar(255),
  "receipt_code" varchar(100),
  "receipt_consignee" varchar(255),
  "receipt_content" varchar(500),
  "receipt_telphone" varchar(255),
  "receipt_title" varchar(200),
  "receipt_type" int4,
  "remark" varchar(500),
  "shop_id" int8,
  "source" int4,
  "taxpayer_id" varchar(40),
  "total" numeric(19,2),
  "trans_code" varchar(255),
  "version" timestamp(6),
  "card_status" int4,
  "customer_no" varchar(255),
  CONSTRAINT "t_so_salesorder_pkey" PRIMARY KEY ("id")
);
CREATE TABLE "public"."t_so_consignee" (
  "id" int8 NOT NULL,
  "address" varchar(500),
  "appoint_time" varchar(100),
  "appoint_time_quantum" varchar(200),
  "appoint_type" varchar(100),
  "area" varchar(200),
  "area_id" int8,
  "buyer_name" varchar(100),
  "buyer_tel" varchar(50),
  "city" varchar(200),
  "city_id" int8,
  "country" varchar(50),
  "country_id" int8,
  "email" varchar(200),
  "mobile" varchar(100),
  "modify_time" timestamp(6),
  "name" varchar(100),
  "order_id" int8,
  "postcode" varchar(50),
  "province" varchar(50),
  "province_id" int8,
  "tel" varchar(50),
  "town" varchar(500),
  "town_id" int8,
  "version" timestamp(6),
  CONSTRAINT "t_so_consignee_pkey" PRIMARY KEY ("id")
);
CREATE TABLE "public"."t_so_orderline" (
  "id" int8 NOT NULL,
  "msrp" numeric(19,2),
  "count" int4,
  "discount" numeric(19,2),
  "discount_price" numeric(19,2),
  "evaluation_status" int4,
  "extention_code" varchar(200) COLLATE "pg_catalog"."default",
  "group_id" int4,
  "item_id" int8,
  "item_name" varchar(100) COLLATE "pg_catalog"."default",
  "item_pic" varchar(4000) COLLATE "pg_catalog"."default",
  "misc" varchar(4000) COLLATE "pg_catalog"."default",
  "order_id" int8,
  "related_item_id" int8,
  "sale_price" numeric(19,2),
  "sale_property" varchar(200) COLLATE "pg_catalog"."default",
  "sku_id" int8,
  "snapshot" int4,
  "subtotal" numeric(19,2),
  "type" int4,
  "version" timestamp(6),
  CONSTRAINT "t_so_orderline_pkey" PRIMARY KEY ("id")
);
CREATE TABLE "public"."t_so_payinfo_log" (
  "id" int8 NOT NULL,
  "amount" numeric(19,2),
  "bankcode" varchar(255),
  "call_close_status" bool,
  "create_time" timestamp(6),
  "modify_time" timestamp(6),
  "order_id" int8,
  "pay_info" varchar(255),
  "pay_info_id" int8,
  "pay_money" numeric(19,2),
  "pay_numerical" numeric(19,2),
  "pay_success_status" bool,
  "pay_type" int4,
  "payment_people" varchar(255),
  "periods" int4,
  "picurl" varchar(255),
  "poundage" numeric(19,2),
  "sub_ordinate" varchar(255),
  "third_pay_account" varchar(255),
  "third_pay_no" varchar(255),
  "thirdpaytype" int4,
  "version" timestamp(6),
  CONSTRAINT "t_so_payinfo_log_pkey" PRIMARY KEY ("id")
);
CREATE TABLE "public"."t_so_payinfo" (
  "id" int8 NOT NULL,
  "amount" numeric(19,2),
  "bankcode" varchar(255),
  "create_time" timestamp(6),
  "modify_time" timestamp(6),
  "order_id" int8,
  "pay_end_time" timestamp(6),
  "pay_info" varchar(255),
  "pay_money" numeric(19,2),
  "pay_numerical" numeric(19,2),
  "pay_start_time" timestamp(6),
  "pay_success_status" bool,
  "pay_type" int4,
  "periods" int4,
  "picurl" varchar(255),
  "poundage" numeric(19,2),
  "third_pay_account" varchar(255),
  "third_pay_no" varchar(255),
  "version" timestamp(6),
  CONSTRAINT "t_so_payinfo_pkey" PRIMARY KEY ("id")
);
CREATE TABLE "public"."t_so_logistics" (
  "id" int8 NOT NULL,
  "is_finish" bool,
  "modify_time" timestamp(6),
  "order_id" int8,
  "tracking_description" text,
  "version" timestamp(6),
  CONSTRAINT "t_so_logistics_pkey" PRIMARY KEY ("id")
);
